site:
  name: Prunus Pharma
  site: 'https://www.prunusafrica.com'
  base: '/'
  trailingSlash: false

  # googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Prunus Pharma
    template: '%s — Prunus'
  description: 'Prunus Pharma is a trusted Kenya-based pharmaceutical company, recognized as one of the top importers, distributors, and wholesalers of high-quality pharma products. With a focus on delivering excellence in the pharmaceutical supply chain, we cater to the healthcare needs of Kenya and East Africa.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Prunus Pharma
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@prunuspharma'
    site: '@prunuspharma'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: UA-248360498-1 # or "G-XXXXXXXXXX"
      partytown: false

ui:
  theme: 'dark:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
