export const products = [
  {
    brand: 'AGYCIN 250 1X6 TAB',
    generic: 'AZITHROMYCIN DIHYDRATE USP EQUIVALENT TO AZITHROMYCIN ANHYDROUS 250 MG',
    form: 'TABLETS',
  },
  {
    brand: 'AGYCIN 500 TAB 1X3',
    generic: 'AZITHROMYCIN DIHYDRATE USP EQUIVALENT TO AZITHROMYCIN ANHYDROUS 500 MG',
    form: 'TABLETS',
  },
  {
    brand: 'AGYCIN SUSP 40ML 1X 40ML',
    generic: 'AZITHROMYCIN DIHYDRATE USP EQUIVALENT TO ANHYDROUS AZITHROMYCIN',
    form: 'SUSPENSION',
  },
  {
    brand: 'ALFENAC P TAB 1X10',
    generic: 'PARACETAMOL 500 MG AND ACECLOFENAC 100 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'AMITONE 200ML 1X200ML',
    generic: 'FERROUS GLYCINE SULPHATE L-HISTIDINE HYDROCHLORIDE H2O BP L-LYSINE HYDROCHLORIDE USP',
    form: 'SYRUP',
  },
  {
    brand: 'ANOMEX SUPP 1X5',
    generic: 'HYDROCORTISONE ACETATE, LIDOCAINE, ZINC OXIDE AND ALLANTOIN',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'ASNORBIN 1000 EFFV TAB 4X4',
    generic: 'VITAMIN C EFFERVECENT TABLETS 1000 MG',
    form: 'TABLETS',
  },
  {
    brand: 'BG GLUTAMIN PLUS TAB 2X10',
    generic: 'VITAMIN B1, VITAMIN B6, VITAMIN B12 WITH L-GLUTAMIC ACID TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'BG GLUTAMIN TAB 1X30',
    generic: 'VITAMIN B1, VITAMIN B6, VITAMIN B12 WITH L-GLUTAMIC ACID TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'BLISCAL SUSP 200 ML',
    generic: 'CALCIUM, MAGNESIUM , ZINC & VITAMIN D3 SUSPENSION',
    form: 'SUSPENSION',
  },
  {
    brand: 'BONAIR HFA INHALER BP 12 GM',
    generic: 'SALBUTAMOL PRESSURISED INHALATION',
    form: 'INHALER',
  },
  {
    brand: 'BROXOL SRP 100 ML 1X100ML',
    generic: 'AMBROXOL HYDROCHLORIDE, GUAIFENESIN, TERBUTALINE SULFATE, CHLORPHENAMINE MALEATE AND MENTHOL',
    form: 'SYRUP',
  },
  {
    brand: 'BROXOL SRP 200 ML 1X200ML',
    generic: 'AMBROXOL HYDROCHLORIDE, GUAIFENESIN, TERBUTALINE SULFATE, CHLORPHENAMINE MALEATE AND MENTHOL',
    form: 'SYRUP',
  },
  {
    brand: 'BYOFER SRP 200 ML 1X200ML',
    generic: 'FERRIC AMMONIUM CITRATE, FOLIC ACID & VITAMIN B12 SYRUP',
    form: 'SYRUP',
  },
  {
    brand: 'CIFEROL D3 DROPS 30ML',
    generic: 'CHOLECALCIFEROL ORAL DROPS 400 IU',
    form: 'DROPS',
  },
  {
    brand: 'CLAMOXIN 1000 TABS BP 2X7',
    generic: 'CO- AMOXICLAV TABLETS BP',
    form: 'TABLETS',
  },
  {
    brand: 'CLAMOXIN 228.5 SUSP 1X100ML',
    generic: 'AMOXICILLIN TRIHYDRATE EQUIVALENT TO AMOXICILLIN CLAVULANATE POTASSIUM USP',
    form: 'SUSPENSION',
  },
  {
    brand: 'CLAMOXIN 625 MG TAB BP 2X7',
    generic: 'AMOXICILLIN 500 MG + CLAVULANIC ACID 125 MG TABLETS USP',
    form: 'TABLETS',
  },
  {
    brand: 'CLOPRONE CRM USP 30GM',
    generic: 'CLOBETASOL PROPIONATE CREAM 0.05% W/W',
    form: 'CREAM',
  },
  {
    brand: 'COMIT 100 TAB 1X4',
    generic: 'SILDENAFIL CITRATE TABLETS 100 MG',
    form: 'TABLETS',
  },
  {
    brand: 'COMIT 50 TAB 1X4',
    generic: 'SILDENAFIL CITRATE TABLETS 50 MG',
    form: 'TABLETS',
  },
  {
    brand: 'CONLAX 10 HDF SUPP USP 1X5',
    generic: 'BISACODYL SUPPOSITORIES USP 10 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'CONLAX 10 SUPP 1X5',
    generic: 'BISACODYL SUPPOSITORIES USP 10 MG SUP',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'CONLAX 5 HDF SUPP USP 1X5',
    generic: 'BISACODYL SUPPOSITORIES USP 5 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'CONLAX 5 SUPP 1X5',
    generic: 'BISACODYL SUPPOSITORIES USP 5 MG SUP',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'DAY BY DAY NAPPY RASH CREAM 20 GM 1X20GM',
    generic: 'DIAPER RASH CREAM 20 GM',
    form: 'CREAM',
  },
  {
    brand: 'FINMOL TAB 1X10',
    generic: 'PARACETAMOL 400 MG + IBUPROFEN 300 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'FLUSAL 125 HFA INHLR MDI 1X1',
    generic: 'FLUTICASONE PROPIONATE AND SALMETEROL PRESSURISED INHALATION',
    form: 'INHALER',
  },
  {
    brand: 'FLUSAL 250 HFA INHLR MDI 1X1',
    generic: 'FLUTICASONE PROPIONATE AND SALMETEROL PRESSURISED INHALATION',
    form: 'INHALER',
  },
  {
    brand: 'FRICKS GINGERLOZ 12X6',
    generic: 'HERBAL GINGER LOZENGES',
    form: 'LOZENGES',
  },
  {
    brand: 'FRICKS LEMON; HONEYLOZ 12X6',
    generic: 'HERBAL HONEY AND LEMON LOZENGES',
    form: 'LOZENGES',
  },
  {
    brand: 'FRICKS MENTHOL LOZ 12X6',
    generic: 'HERBAL MENTHOL LOZENGES',
    form: 'LOZENGES',
  },
  {
    brand: 'FRICKS ORANGE LOZ 12X6',
    generic: 'HERBAL ORANGE LOZENGES',
    form: 'LOZENGES',
  },
  {
    brand: 'FUNBACT A CRM 15GM',
    generic: 'CLOTRIMAZOLE, BETAMETHASONE AND NEOMYCIN SULFATE CREAM',
    form: 'CREAM',
  },
  {
    brand: 'FUNBACT A CRM 30GM',
    generic: 'CLOTRIMAZOLE, BETAMETHASONE AND NEOMYCIN SULFATE CREAM',
    form: 'CREAM',
  },
  {
    brand: 'G DERM CRM 30 GM',
    generic: 'BETAMETHASONE DIPROPIONATE + GENTAMICIN SULPHATE + TOLNAFTATE + IODOCHLORHYDROXYQUINOLINE CREAM',
    form: 'CREAM',
  },
  {
    brand: 'GACET 125 SUPP 2X5',
    generic: 'ACETAMINOPHEN SUPPOSITORIES USP 125 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'GACET 250 SUPP 2X5',
    generic: 'ACETAMINOPHEN SUPPOSITORIES USP 250 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'GLYCERIN 85% 2.0G SUPP USP 2X5',
    generic: 'GLYCERIN SUPPOSITORIES USP 85% W/W',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'GSUNATE 50 HDF SUPP 1X6',
    generic: 'ARTESUNATE SUPPOSITORIES 50 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'GSUNATE 60 INJ WITH DIL',
    generic: 'ARTESUNATE FOR INJECTION 60 MG',
    form: 'INJECTION',
  },
  {
    brand: 'GVFLUC SUSP 35 ML 1X30ML',
    generic: 'FLUCONAZOLE FOR ORAL SUSPENSION 50 MG /5 ML',
    form: 'SUSPENSION',
  },
  {
    brand: 'GVITHER FORTE INJ 6X1 ML',
    generic: 'ARTEMETHER INJECTION 80 MG',
    form: 'INJECTION',
  },
  {
    brand: 'GVITHER INJ 40 MG 10X1 ML',
    generic: 'ARTEMETHER 40 MG INJECTION',
    form: 'INJECTION',
  },
  {
    brand: 'GYNAN FORT PESS 2X5',
    generic: 'METRONIDAZOLE BP NEOMYCIN SULFATE BP NYSTATIN BP',
    form: 'PESSARIES',
  },
  {
    brand: 'GYNOBALANCE PESS 1X5',
    generic: 'LACTOSE MONOHYDRATE BP/PH EUR (1200 MG)',
    form: 'PESSARIES',
  },
  {
    brand: 'HEAL SOFT 30GM 1X30GM',
    generic: 'HEAL SOFT 30GM',
    form: 'CREAM',
  },
  {
    brand: 'HILDERM CH CRM 1X30GM',
    generic: 'SILVER SULFADIAZINE 1 % W/W + CHITOSAN HYDROCHLORIDE 2% W/W CREAM',
    form: 'CREAM',
  },
  {
    brand: 'JUSVIT CAL; VIT D GUM 1X60',
    generic: 'CALCIUM 160 MG AND VITAMIN D 160 IU GUMMIES',
    form: 'GUMMIES',
  },
  {
    brand: 'JUSVIT MULTIVIT GUM 1X60',
    generic: 'MULTIVITAMINS GUMMIES',
    form: 'GUMMIES',
  },
  {
    brand: 'JUSVIT VIT C GUM 1X60',
    generic: 'VITAMIN C GUMMIES 60 MG',
    form: 'GUMMIES',
  },
  {
    brand: 'LOFNAC 100 TAB USP 1X10',
    generic: 'DICLOFENAC SODIUM DELAYED RELEASE TABLETS USP 100 MG',
    form: 'TABLETS',
  },
  {
    brand: 'LOFNAC BALM 12GM',
    generic: 'HERBAL BALM',
    form: 'BALM',
  },
  {
    brand: 'LOFNAC P TAB 1X10',
    generic: 'DICLOFENAC SODIUM 50 MG AND PARACETAMOL 500 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'LOFNAC ROLL ON 20X1X10ML',
    generic: 'HERBAL MUSCLE RELAXANT GEL',
    form: 'GEL',
  },
  {
    brand: 'LOFNAC ROLL ON 30 ML',
    generic: 'HERBAL MUSCLE RELAXANT GEL',
    form: 'GEL',
  },
  {
    brand: 'LONART DISPERSIBLE 20/120 TAB 1X6',
    generic: 'ARTEMETHER 20 MG AND LUMEFANTRINE 120 MG DISPERSIBLE TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'LONART DS 80/480 TAB 1X6',
    generic: 'ARTEMETHER 80 MG AND LUMEFANTRINE 480 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'LONART SUSP 20/120 60 ML 1X60ML',
    generic: 'ARTEMETHER 20 MG AND LUMEFANTRINE 120 MG POWDER FOR ORAL SUSPENSION',
    form: 'SUSPENSION',
  },
  {
    brand: 'LONART TAB 20/120 1X12',
    generic: 'ARTEMETHER 20 MG AND LUMEFANTRINE 120 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'LONART TAB 20/120 1X24',
    generic: 'ARTEMETHER 20MG, LUMEFANTRINE 120MG, TARTRAZINE AND TITANIUM DIOXIDE',
    form: 'TABLETS',
  },
  {
    brand: 'LONART TAB 20/120 3X8',
    generic: 'ARTEMETHER 20MG, LUMEFANTRINE 120MG, TARTRAZINE AND TITANIUM DIOXIDE',
    form: 'TABLETS',
  },
  {
    brand: 'OCORTIN 100 INJ BP 1X10',
    generic: 'HYDROCORTISONE SODIUM SUCCINATE FOR INJECTION BP 100 MG',
    form: 'INJECTION',
  },
  {
    brand: 'P-ALAXIN 40/320 TAB 1X12',
    generic: 'DIHYDROARTEMISININ AND PIPERAQUINE PHOSPHATE 240 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'P-ALAXIN 40/320 TAB 1X15',
    generic: 'DIHYDROARTEMISININ AND PIPERAQUINE PHOSPHATE TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'P-ALAXIN 40/320 TAB 1X9',
    generic: 'DIHYDROARTEMISININ 40 MG AND PIPERAQUINE PHOSPHATE 320 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'P-ALAXIN DS 120/960 TAB 1X3',
    generic: 'DIHYDROARTEMISININ 120 MG AND PIPERAQUINE PHOSPHATE 960 MG TABLETS',
    form: 'TABLETS',
  },
  {
    brand: 'P-ALAXIN SUSP 80/640 80 ML 1X80ML',
    generic: 'DIHYDROARTEMISININ 80 MG AND PIPERAQUINE PHOSPHATE 640 MG POWDER FOR ORAL SUSPENSION',
    form: 'SUSPENSION',
  },
  {
    brand: 'PIP OFF GEL USP 25 GM',
    generic: 'CLINDAMYCIN PHOSPHATE GEL USP 1% W/W',
    form: 'GEL',
  },
  {
    brand: 'SANFOTAX- 1000',
    generic: 'CEFTRIAXONE FOR USP 1000MG EACH VIAL, SODIUM USP EQUIVALENT TO ANHYDROUS',
    form: 'INJECTION',
  },
  {
    brand: 'SANFUROX 500 TAB USP 1X10',
    generic: 'CEFUROXIME AXETIL TABLETS USP 500 MG',
    form: 'TABLETS',
  },
  {
    brand: 'SANFUROX 750 MG INJ USP',
    generic: 'CEFUROXIME FOR INJECTION USP 750 MG',
    form: 'INJECTION',
  },
  {
    brand: 'SANTRIAX 1000 INJ USP',
    generic: 'CEFTRIAXONE FOR INJECTION USP 1000 MG',
    form: 'INJECTION',
  },
  {
    brand: 'SECNAGYL TAB 1X2',
    generic: 'SECNIDAZOLE TABLETS 1 GM',
    form: 'INJECTION',
  },
  {
    brand: 'SURDEX SRP 120 ML 1X120ML',
    generic: 'PARACETAMOL, CHLORPHENAMINE MALEATE AND PHENYLEPHRINE HYDROCHLORIDE SYRUP',
    form: 'SYRUP',
  },
  {
    brand: 'SURDEX SRP 60 ML 1X60 ML',
    generic: 'PARACETAMOL, CHLORPHENAMINE MALEATE AND PHENYLEPHRINE HYDROCHLORIDE SYRUP',
    form: 'SYRUP',
  },
  {
    brand: 'TODAY INTIMATE HYGIENE 100ML 1X100ML',
    generic: 'LACTIC ACID',
    form: 'LIQUID',
  },
  {
    brand: 'TODAY INTIMATE HYGIENE 7ML',
    generic: 'LACTIC ACID',
    form: 'LIQUID',
  },
  {
    brand: 'TODAY PEG PESS 1X5',
    generic: 'NONOXYNOL-9 VAGINAL CONTRACEPTIVE',
    form: 'PESSARIES',
  },
  {
    brand: 'VAGID 200 PEG BP 1X3',
    generic: 'CLOTRIMAZOLE PESSARIES BP 200 MG',
    form: 'PESSARIES',
  },
  {
    brand: 'VAGID 500 HDF BP 1X1',
    generic: 'CLOTRIMAZOLE PESSARIES BP 500 MG',
    form: 'PESSARIES',
  },
  {
    brand: 'VAGID CL PEG SUPP 1X3',
    generic: 'CLINDAMYCIN 100 MG AND CLOTRIMAZOLE 200 MG VAGINAL SUPPOSITORIES',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'VAGID PEG PESS BP 1X6',
    generic: 'CLOTRIMAZOLE PESSARIES BP 100 MG',
    form: 'PESSARIES',
  },
  {
    brand: 'VOMITIN 10 PEG SUPP 1X5',
    generic: 'DOMPERIDONE SUPPOSITORIES 10 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'VOMITIN 30 PEG SUPP 1X5',
    generic: 'DOMPERIDONE SUPPOSITORIES 30 MG',
    form: 'SUPPOSITORY',
  },
  {
    brand: 'X-TONE DROPS 30ML',
    generic: 'ESSENTIAL AMINO ACIDS WITH VITAMIN C DROPS',
    form: 'DROPS',
  },
  {
    brand: 'X-TONE FORTE SRP 200 ML',
    generic: 'AMINO ACIDS + MULTIVITAMIN SYRUP',
    form: 'SYRUP',
  },
];
